Yasir Kereci NLayer Proje/CvPortf/Controllers/FeatureController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace CvPortf.Controllers
{
    public class FeatureController : Controller
    {
        FeatureManager featureManager = new FeatureManager(new EfFeatureDal());
        [HttpGet]
        public IActionResult Index()
        {
            var values = featureManager.TGetByID(1);
            return View(values);
        }
        
        [HttpPost]
        public IActionResult Index(Feature feature)
        {
            featureManager.TUpdate(feature);
            return RedirectToAction("Index","Default");
        }
    }
}

Yasir Kereci NLayer Proje/CvPortf/Views/Feature/Index.cshtml
@model EntityLayer.Concrete.Feature
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@*<div class="card-header border-0">
    <h3 class="mb-0">Öne Çıkan Post Düzenleme Sayfası</h3>
</div>*@

@using (Html.BeginForm("Index", "Feature", FormMethod.Post))
{
    @Html.HiddenFor(x => x.FeatureID)
    <br />
    <label>Başlık</label>
    @Html.TextBoxFor(x => x.Header, new { @class = "form-control" })
    <br />
    <label>Ad Soyad</label>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <label>Pozisyon</label>
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
    <a asp-action="Index" asp-controller="Feature" class="btn btn-dark">İptal</a>
}